version: "3.7"
services:
  worker:
    build: 
      dockerfile: Dockerfile.dev
      context: ./worker
    restart: always
    expose:
      - "8080"
    ports:
      - "8080"
    volumes:
      - .:/app
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./api
    restart: always
    expose:
      - "9090"
    ports:
      - "9090:9090"
    volumes:
      - .:/app
  Balancer:
    image: nginx:1.15.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - worker
      - api
    ports:
      - "5000:5000"